# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 14:21
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0003_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='taskmanager.Profile', verbose_name='user')),
            ],
            options={
                'verbose_name': 'Tag',
                'ordering': ('user', 'name'),
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.AlterField(
            model_name='project',
            name='color',
            field=models.CharField(default='#fff', help_text='Enter the hex colour code, like #ccc or #cccccc', max_length=7, validators=[django.core.validators.RegexValidator('(^#[0-9a-fA-F]{3}$)|(^#[0-9afA-F]{6}$)')], verbose_name='color'),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together=set([('user', 'name')]),
        ),
    ]
